[package]
name = "websocket-server"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
config = "0.11"
futures = "0.3"
dotenv = "0.15"
lazy_static = "1.4.0"

[server]
address = "127.0.0.1"
port = 3030
